l10n.addResource('en_us', {
    "Home": "Home",
    "Settings": "Settings",
    "Management": "Management",
    "Dashboard": "Dashboard",
    "History": "History",
    "Realtime": "Realtime",
    "Messages": "Messages",
    "Password": "Password",
    "QuartzX": "RFID Data Management System",
    "Global": "Global",
    "Total": "Total",
    "About": "About",
    "Version": "Version",
    "Communication Error": "Communication Error",
    "Box Content Settings": "Box Settings",
    "Block Content Settings": "Block",
    "Gas Content Settings": "Block/Gas Settings",
    "Language": "Language",
    "None": "N/A",
    "Monitor": "Monitor",
    "Property": "Property",
    "Value": "Value",
    "Block Name": "Block Name",
    "Gas": "Gas",
    "Save": "Save",
    "Time": "Time",
    "Status": "Status",
    "MPa": "MPa",
    "Pa": "Pa",
    "Day": "Days",
    "Search": "Search",
    "Fail": "Sensor Fail",
    "Danger": "Danger",
    "ExLow": "Very Low",
    "Low": "Low",
    "Normal": "Normal",
    "High": "High",
    "ExHigh": "Very High",
    "Login": "Login",
    "Username": "Username",
    "Password": "Password",
    "Authentication Fail": "Authentication Fail",
    "Password Setting": "Password Setting",
    "Old Password": "Old Password",
    "New Password": "New Password",
    "New Password Again": "New Password Again",
    "New password mismatch": "New password mismatch",
    "Password can't be empty": "Password can't be empty",
    "Password min length": "Password length must great then 6",
    "Save success": "Save success",
    "Apply": "Apply",
    "OK": "OK",
    "Cancel": "Cancel",
    "Database": "Database",
    "Service": "System Service",
    "Server": "Server",
    "System Status": "System Status",
    "Dongle": "Dongle",
    "Error": "Error",
    "Warning": "Warning",
    "Unknown": "Unknown",
    "ms": "ms",
    "TimeZone": "Time Zone",
    "MessageCount": "Message Count",
    "Chart": "Line Chart",
    "Data": "Realtime Data",
    "Frequency": "Frequency",
    "Address": "Room1001 No.966 GongHe Xin Road, Shanghai, China",
    "Corporation": "Shanghai Quartzx electronical technical Co.,Ltd."
});