l10n.addResource('zh_cn', {
    "Home": "首页",
    "Settings": "设置",
    "Management": "管理",
    "Dashboard": "概况",
    "History": "历史",
    "Realtime": "实时",
    "Messages": "消息",
    "Password": "密码",
    "QuartzX": "RFID数据管理系统",
    "Global": "全局",
    "Total": "总数",
    "About": "关于",
    "Version": "版本",
    "Communication Error": "通讯失败",
    "Box Content Settings": "报警箱设置",
    "Block Content Settings": "区域",
    "Gas Content Settings": "区域/气体设置",
    "Language": "语言",
    "None": "无效",
    "Monitor": "监控",
    "Property": "属性",
    "Value": "值",
    "Block Name": "区域名称",
    "Gas": "气体",
    "Save": "保存",
    "Time": "时间",
    "Status": "状态",
    "MPa": "兆帕",
    "Pa": "帕斯卡",
    "Day": "天",
    "Search": "查询",
    "Fail": "传感器失效",
    "Danger": "危险",
    "ExLow": "低",
    "Low": "偏低",
    "Normal": "正常",
    "High": "偏高",
    "ExHigh": "高",
    "Login": "登录",
    "Username": "用户",
    "Password": "密码",
    "Authentication Fail": "认证失败",
    "Password Setting": "密码设置",
    "Old Password": "旧密码",
    "New Password": "新密码",
    "New Password Again": "确认新密码",
    "New password mismatch": "新密码不一致",
    "Password can't be empty": "密码不能为空",
    "Password min length": "密码至少6位",
    "Save success": "保存成功",
    "Apply": "应用",
    "OK": "确认",
    "Cancel": "取消",
    "Database": "数据库",
    "Service": "系统服务",
    "Server": "服务器",
    "System Status": "系统状态",
    "Dongle": "加密狗",
    "Error": "错误",
    "Warning": "异常",
    "Unknown": "未知",
    "ms": "毫秒",
    "TimeZone": "时区",
    "MessageCount": "消息数量",
    "Chart": "曲线图",
    "PieChart": "饼图",
    "BarChart": "柱状图",
    "LineChart": "折线图",
    "Data": "实时数据",
    "Frequency": "频率",
    "FilterRule": "过滤规则",
    "Address": "上海市静安区共和新路966号1001室",
    "Corporation": "上海晶菁电子科技有限公司"
});